### ISSUE TITLE
Not usable. Many bugs and resources missing.

### ISSUE THREAD

**Issue by sharan21** [yixinL7/Direct-Style-Transfer#4]
The code doesn't work out of the box at all. There are many code errors and errors for missing resources/directories and pretrained models. For e.g. on running bootstrap.py, there is an error in Line 67 where the GPTTokenizer needs load an object from a './gpt' folder which is missing. There is no documentation about where to obtain these dependencies.

Please include all these or update the documentation with steps on how to obtain all dependencies. I am not able to find any of the GPT Tokenizers needed on HuggingFace.

**Comment by yixinL7** [comment]
The purpose of this repo is mainly to make the outputs and design choices public available so it is not actively maintained and the code was released as-is. As recently I received a request of sharing all the trained models, I will share these here which might be helpful:
I've put all the trained model checkpoints and a minimum context (including code, processed data, and auxiliary models) for evaluation in this google drive [folder](https://drive.google.com/drive/folders/122ulQvb9FVHXQE3mvkEcfxitb2FxOODu?usp=sharing). The zip file in it contains the working context (a folder), and all other folders contain the model checkpoints that can be loaded using torch.load() (the folder names should be self-explanatory). 
Several notes:

- I used Transformers 2.4.0 and PyTorch 1.2.0 for the experiments.
- evaluate.py is the main evaluation file. To evaluate the performance of a trained checkpoint, you could run `python evaluate.py --cuda --gpuid GPUID --file NAME_OF_THE_OUTPUT_FILE --dataset NAME_OF_THE_DATASET (yelp, amazon, imdb) --model_pt PATH_TO_THE_MODEL_CHECKPOINT`
- Compared to the original GPT-2 model, I modified the token embedding matrix to only include the tokens that appear in the training set to save memory usage. Therefore the checkpoints cannot be used to initialize the original GPT-2 model.
- I was able to reproduce the evaluation results reported in our paper using the context I mentioned above, except on Yelp the results are slightly different.

Good luck with your project!

**Comment by sharan21** [comment]
Thank you for the reply. There is just one more issue that is preventing me from training. It seems like you have done another data preprocessing step on each dataset. You have converted files of form e.g. sentiment.train.0 -> sentiment-gpt.train.json. However, I cannot see any code which automates this preprocessing step. 

This is preventing me from training or even evaluating using the checkpoints you have given. Please do mention how to perform this json conversion step. Also, I am getting state dict mismatch errors while trying to load from checkpoints. I think this is because my config.json is not set correctly. Please do provide the config.json files for the corresponding checkpoints you have uploaded in google drive. 

Please do help me at the earliest.

**Comment by sharan21** [comment]
Please ignore the second point in my previous comment regarding "state dict mismatch errors". Turns out it was a versioning issue. However the first issue regarding unfound sentiment-gpt* files is still there so assist me with that. Thanks

**Comment by Dinxin** [comment]
What is the version of transformers module ?

**Comment by Dinxin** [comment]
@sharan21 How did you solve the problem of "state dict mismatch errors"?
